### ISSUE TITLE
SIGSEGV when bsLCat is called 

### ISSUE THREAD

**Issue by traderbagel** [jserv/facebooc#11]
When the first time `bsLCat` function being called, system crash due to segmentation fault.
i ran this program on macintosh and following is message from gdb

```
#0  0x00007fff93bde152 in strlen () from /usr/lib/system/libsystem_c.dylib
#1  0x0000000100003789 in bsLCat (orig=0x7fff5fbfa8c0,
    s=0x400531 <error: Cannot access memory at address 0x400531>)
    at src/bs.c:127
#2  0x0000000100001753 in templateRender (template=0x100400450)
    at src/template.c:62
#3  0x00000001000032cb in home (req=<optimized out>) at src/main.c:169
#4  0x0000000100006029 in handle (server=0x100100020, fd=<optimized out>,
    activeFDs=<optimized out>, addr=<optimized out>) at src/server.c:185
#5  serverServe (server=0x100100020) at src/server.c:247
#6  0x0000000100001c7b in main (argc=<optimized out>, argv=<optimized out>)
    at src/main.c:135
```

**Comment by jserv** [comment]
Fixed by Rudy.
